name: Exercice 3
on: [push, workflow_dispatch]
jobs:
  ex3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ouech ${{ github.actor.login }} event."
      - uses: actions/checkout@v3
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - uses: docker/setup-docker-action@v4
      - name: install java
        run: mvn clean install
      - name: docker build
        run: docker build -t exercice3:${{ github.git_hash }} .
